name: CI-CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: self-hosted

    env:
      DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and Push Backend Image
        shell: bash
        run: |
          docker build -t ${DOCKER_USER,,}/devops-backend:latest ./backend
          docker push ${DOCKER_USER,,}/devops-backend:latest

      - name: Build and Push Frontend Image
        shell: bash
        run: |
          docker build -t ${DOCKER_USER,,}/devops-frontend:latest ./frontend
          docker push ${DOCKER_USER,,}/devops-frontend:latest

      - name: Email on Success
        if: success()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: "CI/CD Pipeline Success"
          to: ${{ secrets.NOTIFY_EMAIL }}
          from: GitHub Actions <${{ secrets.SMTP_USERNAME }}>
          body: |
            Hello,

            The CI/CD pipeline completed successfully.

            Repository : ${{ github.repository }}
            Branch     : ${{ github.ref_name }}
            Commit SHA : ${{ github.sha }}
            Workflow   : ${{ github.workflow }}
            Run ID     : ${{ github.run_id }}

            Docker images were built and pushed successfully.

            Regards,
            GitHub Actions

      - name: Email on Failure
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: "CI/CD Pipeline Failed"
          to: ${{ secrets.NOTIFY_EMAIL }}
          from: GitHub Actions <${{ secrets.SMTP_USERNAME }}>
          body: |
            Hello,

            The CI/CD pipeline has failed.

            Repository : ${{ github.repository }}
            Branch     : ${{ github.ref_name }}
            Commit SHA : ${{ github.sha }}
            Workflow   : ${{ github.workflow }}
            Run ID     : ${{ github.run_id }}

            Please review the GitHub Actions logs.

            Regards,
            GitHub Actions
