name: CI-CD Pipeline (Windows Only - DEBUG)

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: [self-hosted, windows]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # ---- HARD-CODED DEBUG LOGIN (TEMPORARY) ----
      - name: Docker Login (DEBUG)
        shell: cmd
        run: |
          echo dckr_pat_RxYJQSJhEN0dt1-cULf49KbTFrc | docker login -u mohitsaini --password-stdin

      # ---- Build & Push Backend ----
      - name: Build & Push Backend
        shell: cmd
        run: |
          docker build -t mohitsaini/devops-backend:latest backend
          docker push mohitsaini/devops-backend:latest

      # ---- Build & Push Frontend ----
      - name: Build & Push Frontend
        shell: cmd
        run: |
          docker build -t mohitsaini/devops-frontend:latest frontend
          docker push mohitsaini/devops-frontend:latest
