name: Hello World CI

on:
  push:
    branches:
      - main

jobs:
  hello:
    runs-on: self-hosted
    steps:
      - name: Hello World Step
        shell: pwsh
        run: |
          Write-Host "Hello World from Windows Self-Hosted Runner"
