name: Hello World CI

on:
  push:
    branches: [ main ]

jobs:
  hello:
    runs-on: self-hosted
    steps:
      - name: Print Hello World
        shell: powershell
        run: Write-Output "Hello World from Self-Hosted Runner"
